#! /bin/bash
# -*- ENCODING: UTF-8 -*-
#·

# lssubdir
# lista los sub-directorios

if [ -z "$1" ]; then
	directorio="./"
elif [ ! -d "$1" ]; then
	echo "El directorio $1 no existe"
	exit 1
else
	directorio="$1/"
fi

directorio="$(readlink -f "$directorio")/"

lectura=$(find "$directorio" -maxdepth 1 -type d ! -path "$directorio")
if [ ${#lectura} -eq 0 ]; then
	#Si no hay subdirectorios
	exit 2
fi

oldIFS=$IFS
IFS=$'\n'

while read -a subdir; do
	if [ -d "$subdir" ]; then
		echo "$subdir"
	fi
done <<< "$lectura"

IFS=$oldIFS
