#! /bin/bash
# -*- ENCODING: UTF-8 -*-
#·

# checksum

if [ ${#} -lt 1 ]; then
	echo -e "\tFalta el fichero de entrada"
	exit 1
fi

if [ ! -r "$1" ]; then
	echo "El fichero $1 no se puede leer"
	exit 2
fi

default="crc"
modo=${2:-$default}
case "$modo" in
    crc)
        cksum "$1"
        ;;
    md5)
        md5sum "$1"
        ;;
    sha1)
        sha1sum "$1"
        ;;
    sha256)
        sha256sum "$1"
        ;;
    *)
        echo "Modo '$2' desconocido"
        exit 1
        ;;
esac
exit 2
