#! /bin/bash
# -*- ENCODING: UTF-8 -*-
#·
#######################################################
#			        lsusbdiscs
#------------------------------------------------------
#	Lista los discos usb
#------------------------------------------------------
# autor:	Simón Martínez <simon@cicoss.net>
#######################################################

ahora=$(date)

printf '\055%.0s' {1..80}

echo -en "\n\e[1;37m"
printf '%-40s%40s' "$0" "$ahora"
echo -en "\e[0m\n"

printf '\055%.0s' {1..80}; echo ""

lsblk -o NAME,TYPE,SIZE,MODEL,MOUNTPOINT

printf '\055%.0s' {1..80}; echo ""
