#! /bin/bash
# -*- ENCODING: UTF-8 -*-
# ·
#######################################################
#			fsuuid
#------------------------------------------------------
#	Muestra el UUID del sistema de ficheros
#------------------------------------------------------
# autor:	Simón Martínez <simon@cicoss.net>
#------------------------------------------------------
# Uso:
# 	fsuuid [device | directorio | fichero]
#
#	si no se especifica será el directorio actual
#
#	Requiere del script indev
#
#######################################################

if [ -z "$1" ]; then
	origen=$(realpath ".")
else
	origen=$(realpath "$1")
fi

sudo lsblk -n -o UUID $(indev -s "$origen")
