#! /bin/bash
# -*- ENCODING: UTF-8 -*-
# ·
#######################################################
#			indev
#------------------------------------------------------
#	Muestra el dispositivo en el que descansa
#		el fichero o directorio
#------------------------------------------------------
# autor:	Simón Martínez <simon@cicoss.net>
#------------------------------------------------------
# Uso:
# 	indev [-s] [directorio | file]
#
#	Si no se especifica será el directorio actual
#	-s Salida concisa. Solo el nombre del
#		dispositivo
#
#######################################################

if [ $# -eq 0 ]; then
	modo="verbose"
elif [ "$1" = "-s" ]; then
	modo="conciso"
	shift
else
	modo="verbose"
fi

if [ $# -ne 0 ]; then
	origen=$(realpath "$1")
else
	origen=$(realpath ".")
fi

if [ ! -d "$directorio" ]; then
	#Si no es un directorio nos quedamos solo con la ruta
	directorio=$(dirname "$origen")
fi

if [ "$modo" = "verbose" ]; then
	echo "'$origen' está en:"
	printf '\055%.0s' {1..80}; echo ""
	df -hT $directorio
else
	df $directorio | cut -d " " -f 1 | grep "/"
fi
