#! /bin/bash
# -*- ENCODING: UTF-8 -*-
# ·
#######################################################
#			label
#------------------------------------------------------
#	Muestra la etiqueta de la partición
#------------------------------------------------------
# autor:	Simón Martínez <simon@cicoss.net>
#------------------------------------------------------
# Uso:
# 	label [device | directorio | fichero]
#
#	si no se especifica será el directorio actual
#
#	Requiere del script indev
#
#######################################################

if [ -z "$1" ]; then
	origen=$(realpath ".")
else
	origen=$(realpath "$1")
fi

sudo lsblk -n -o LABEL $(indev -s "$origen")
