#! /bin/bash
# -*- ENCODING: UTF-8 -*-
# ·
#######################################################
#			lsdiscs
#------------------------------------------------------
#	Muestra los discos en el sistema
#------------------------------------------------------
# autor:	Simón Martínez <simon@cicoss.net>
#######################################################

ahora=$(date)

cabecera=$(printf '\055%.0s' {1..80})
cabecera+="\n\e[1;37m$0\t$ahora\e[0m\n"
cabecera+=$(printf '\055%.0s' {1..80})

echo -en "$cabecera\n"

lsblk -io KNAME,TYPE,SIZE,MODEL | grep -e "KNAME" -e "disk"

echo -en "$(printf '\055%.0s' {1..80})"
