#! /bin/bash
# -*- ENCODING: UTF-8 -*-
# ·
#######################################################
#			lsmounts
#------------------------------------------------------
#	Muestra particiones montadas
#------------------------------------------------------
# autor:	Simón Martínez <simon@cicoss.net>
#######################################################

ahora=$(date)

if [ -z $1 ] || [ "$1" != "-s" ]; then
	ordena="NO"
else
	ordena="SI"
fi

printf '\055%.0s' {1..80}

echo -en "\n\e[1;37m"
printf '%-40s%40s' "$0" "$ahora"
echo -en "\e[0m\n"

printf '\055%.0s' {1..80}; echo ""

declare devices=$(df -h | grep -E "^/dev/|@" | cut -d " " -f 1 | sort -k1)
declare -a devmontados=()

tmpfile1=$(mktemp /tmp/DispositivosMontados.XXXXXX)
trap "rm -f -- "$tmpfile1"" INT TERM HUP EXIT

for d in $devices; do
	findmnt -c -o SOURCE,TARGET $d | grep -E "^/dev/|@" >>$tmpfile1
done

tmpfile2=$(mktemp /tmp/DispositivosMontadosSort.XXXXXX)
trap "rm -f -- "$tmpfile2"" INT TERM HUP EXIT

if [ "$ordena" == "SI" ]; then
	cat $tmpfile1 | sort -k2 >>$tmpfile2
else
	cat $tmpfile1 >>$tmpfile2
fi

while read linea; do
   printf "%-30s -> %s\n" $linea
done < $tmpfile2

printf '\055%.0s' {1..80}; echo ""
