#! /bin/bash
# -*- ENCODING: UTF-8 -*-
#·
#######################################################
#			        lspart
#------------------------------------------------------
#	Lista los particiones disponibles
#------------------------------------------------------
# autor:	Simón Martínez <simon@cicoss.net>
#######################################################

ahora=$(date)

cabecera=$(printf '\055%.0s' {1..80})
cabecera+="\n\e[1;37m$0\t$ahora\e[0m\n"
cabecera+=$(printf '\055%.0s' {1..80})

echo -en "$cabecera\n"

lsblk -io KNAME,TYPE,SIZE,MOUNTPOINT | grep -e "KNAME" -e "part" -e "crypt"

echo -en "$(printf '\055%.0s' {1..80})"
