#! /bin/bash
# -*- ENCODING: UTF-8 -*-
#·
#######################################################
#			        lspart
#------------------------------------------------------
#	Lista los particiones disponibles
#------------------------------------------------------
# autor:	Simón Martínez <simon@cicoss.net>
#######################################################

ahora=$(date)

printf '\055%.0s' {1..80}

echo -en "\n\e[1;37m"
printf '%-40s%40s' "$0" "$ahora"
echo -en "\e[0m\n"

printf '\055%.0s' {1..80}; echo ""

lsblk -io KNAME,TYPE,SIZE,MOUNTPOINT | grep -e "KNAME" -e "part" -e "crypt"

printf '\055%.0s' {1..80}; echo ""
