#! /bin/bash
# -*- ENCODING: UTF-8 -*-
#·
#######################################################
#			        lsusbdiscs
#------------------------------------------------------
#	Lista los discos usb
#------------------------------------------------------
# autor:	Simón Martínez <simon@cicoss.net>
#######################################################

ahora=$(date)

cabecera=$(printf '\055%.0s' {1..80})
cabecera+="\n\e[1;37m$0\t$ahora\e[0m\n"
cabecera+=$(printf '\055%.0s' {1..80})

echo -en "$cabecera\n"

grep -Ff <(sudo hwinfo --disk --short) <(sudo hwinfo --usb --short) | grep -v "disk:"

echo -en "$(printf '\055%.0s' {1..80})"
