#! /bin/bash
# -*- ENCODING: UTF-8 -*-
# ·
#######################################################
#					selereg
#------------------------------------------------------
#	selecciona nombre de ficheros con exp. regulares
#------------------------------------------------------
# autor:	Simón Martínez <simon@cicoss.net>
#######################################################

if [ -z $1 ]; then
	echo "Introduzca una expresión"
	exit 1
fi

oldIFS="$IFS"
IFS=$'\n'

for arch in $(find . -maxdepth 1 -type f -iname "*.jpg" | grep "[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}[ |_]");do 
	echo "$arch"; 
done

IFS=$oldIFS