#! /bin/bash
# -*- ENCODING: UTF-8 -*-
# ·
#######################################################
#			sizediscs
#------------------------------------------------------
#	Muestra el uso de los discos
#------------------------------------------------------
# autor:	Simón Martínez <simon@cicoss.net>
#######################################################

ahora=$(date)

cabecera=$(printf '\055%.0s' {1..80})
cabecera+="\n\e[1;37m$0\t$ahora\e[0m\n"
cabecera+=$(printf '\055%.0s' {1..80})

echo -en "$cabecera\n"

df -hT | grep -e "/dev/sd" -e "/dev/mapper" -e "@" -e "Usados" -e "Used"

echo -en "$(printf '\055%.0s' {1..80})"
