#! /bin/bash
# -*- ENCODING: UTF-8 -*-
# ·
#######################################################
#			sizediscs
#------------------------------------------------------
#	Muestra el uso de los discos
#------------------------------------------------------
# autor:	Simón Martínez <simon@cicoss.net>
#######################################################

ahora=$(date)

printf '\055%.0s' {1..80}
echo -en "\n\e[1;37m"
printf '%-40s%40s' "$0" "$ahora"
echo -en "\e[0m\n"
printf '\055%.0s' {1..80}; echo ""

df -hT | grep -e "/dev/sd" -e "/dev/mapper" -e "@" -e "Usados" -e "Used"

printf '\055%.0s' {1..80}; echo ""
