#! /bin/bash
# -*- ENCODING: UTF-8 -*-
# ·
#######################################################
#			verifySHA256
#------------------------------------------------------
#	verifica la suma de verificación proporcionada
#	en un nombre-fichero.SHA256
#
#------------------------------------------------------
# autor:	Simón Martínez <simon@cicoss.net>
#------------------------------------------------------
# Uso:
# 	verifysum nombre-fichero
#
#######################################################

if [ $# -lt 1 ]; then
	echo "Uso:"
	echo "$0 nombre-fichero"
	exit 1
fi

if [ ! -f "$1.SHA256" ]; then
	echo "'$1.SHA256' no es un fichero o no se encuentra"
	exit 1
else
	nombre="$1.SHA256"
fi

r=$(sha256sum -c "$nombre" 2>&1)

if [ $? -ne 0 ]; then
	echo "La suma de verificación falló"
	exit 1
else
	echo "Verificación correcta"
	exit 0
fi
